"""Core node primitives and protocol types for graphrefly."""

from graphrefly.core.clock import monotonic_ns, wall_clock_ns
from graphrefly.core.dynamic_node import DynamicNodeImpl, dynamic_node
from graphrefly.core.guard import (
    Actor,
    GuardAction,
    GuardDenied,
    GuardFn,
    access_hint_for_guard,
    compose_guards,
    normalize_actor,
    policy,
    record_mutation,
    system_actor,
)
from graphrefly.core.meta import describe_node, meta_snapshot
from graphrefly.core.node import (
    Node,
    NodeActions,
    NodeFn,
    NodeImpl,
    NodeStatus,
    SubscribeHints,
    node,
)
from graphrefly.core.protocol import (
    DeferWhen,
    EmitStrategy,
    Message,
    Messages,
    MessageType,
    batch,
    dispatch_messages,
    emit_with_batch,
    is_batching,
    is_phase2_message,
    is_terminal_message,
    message_tier,
    partition_for_batch,
    propagates_to_meta,
)
from graphrefly.core.subgraph_locks import (
    acquire_subgraph_write_lock,
    acquire_subgraph_write_lock_with_defer,
    defer_down,
    defer_set,
    ensure_registered,
    union_nodes,
)
from graphrefly.core.sugar import (
    PipeOperator,
    derived,
    effect,
    pipe,
    producer,
    state,
)

__all__ = [
    "Actor",
    "DynamicNodeImpl",
    "DeferWhen",
    "EmitStrategy",
    "GuardAction",
    "GuardDenied",
    "GuardFn",
    "Message",
    "MessageType",
    "Messages",
    "Node",
    "PipeOperator",
    "NodeActions",
    "NodeFn",
    "NodeImpl",
    "NodeStatus",
    "SubscribeHints",
    "monotonic_ns",
    "wall_clock_ns",
    "access_hint_for_guard",
    "acquire_subgraph_write_lock",
    "acquire_subgraph_write_lock_with_defer",
    "batch",
    "compose_guards",
    "defer_down",
    "defer_set",
    "describe_node",
    "dispatch_messages",
    "emit_with_batch",
    "ensure_registered",
    "is_batching",
    "is_phase2_message",
    "is_terminal_message",
    "message_tier",
    "propagates_to_meta",
    "meta_snapshot",
    "node",
    "normalize_actor",
    "partition_for_batch",
    "policy",
    "record_mutation",
    "system_actor",
    "union_nodes",
    "dynamic_node",
    "derived",
    "effect",
    "pipe",
    "producer",
    "state",
]
