#!/usr/bin/env python3
"""Generate Starlight API pages from Python source docstrings."""

from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from griffe import Alias, Attribute, Class, Function, TypeAlias, load

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
PACKAGE = SRC / "graphrefly"
WEBSITE = ROOT / "website"
API_DIR = WEBSITE / "src" / "content" / "docs" / "api"
GENERATED_DIR = WEBSITE / "src" / "generated"
SIDEBAR_PATH = GENERATED_DIR / "api-sidebar.mjs"
MARKER = "<!-- generated by website/scripts/gen-api-docs.py; do not edit -->"


@dataclass(frozen=True)
class ApiPage:
    name: str
    slug: str
    category: str
    markdown: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_if_changed(path: Path, text: str, check: bool, changed: list[str]) -> None:
    if path.exists() and read_text(path) == text:
        return
    changed.append(str(path.relative_to(ROOT)))
    if check:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def exported_names() -> list[str]:
    module = ast.parse(read_text(PACKAGE / "__init__.py"), filename=str(PACKAGE / "__init__.py"))
    for node in module.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    return [
                        item.value
                        for item in node.value.elts
                        if isinstance(item, ast.Constant) and isinstance(item.value, str)
                    ]
    raise SystemExit("graphrefly.__all__ is missing or not a literal string list")


def slug_for(name: str) -> str:
    slug = re.sub(r"[^a-z0-9_]+", "-", name.lower()).strip("-")
    return slug or "symbol"


def unique_slug_for(name: str, obj: Any, slug_counts: dict[str, int], used: set[str]) -> str:
    base = slug_for(name)
    if slug_counts.get(base, 0) <= 1:
        return base

    kind = object_kind(target_for(obj)).replace(" ", "-")
    candidate = f"{base}-{kind}"
    if candidate not in used:
        return candidate

    index = 2
    while f"{candidate}-{index}" in used:
        index += 1
    return f"{candidate}-{index}"


def target_for(obj: Any) -> Any:
    if isinstance(obj, Alias):
        try:
            return obj.final_target
        except Exception:
            return obj
    return obj


def object_kind(obj: Any) -> str:
    if isinstance(obj, Class):
        return "class"
    if isinstance(obj, Function):
        return "function"
    if isinstance(obj, TypeAlias):
        return "type alias"
    if isinstance(obj, Attribute):
        return "attribute"
    if isinstance(obj, Alias):
        return "alias"
    return type(obj).__name__.lower()


def category_for(name: str, obj: Any) -> str:
    if name.startswith("Wire") or name.startswith("wire_"):
        return "Wire Bridge"
    if name.startswith("Http") or name.startswith("LocalHttp") or name.startswith("Sse"):
        return "Async and Network"
    if name in {
        "AsyncRunner",
        "anyio_runner",
        "async_node",
        "asyncio_runner",
        "from_async_iter",
        "from_awaitable",
        "from_http",
        "from_sse",
        "trio_runner",
    }:
        return "Async and Network"
    if name.startswith("Restore") or name.startswith("restore_") or name == "GraphCheckpoint":
        return "Restore"
    if name.endswith("Error") or name.endswith("CallbackError") or name == "DataIssue":
        return "Exceptions and Issues"
    if name in {
        "ControlMessage",
        "DataMessage",
        "ErrorMessage",
        "Message",
        "SENTINEL",
        "Sentinel",
    }:
        return "Messages and Data"
    if name in {"version", "__version__"}:
        return "Utilities"
    return "Core Facade"


def signature_for(obj: Any) -> str | None:
    if hasattr(obj, "signature"):
        try:
            return str(obj.signature())
        except Exception:
            return None
    return None


def annotation_for(obj: Any) -> str | None:
    annotation = getattr(obj, "annotation", None)
    if annotation is None:
        return None
    return str(annotation)


def value_for(obj: Any) -> str | None:
    value = getattr(obj, "value", None)
    if value is None:
        return None
    return str(value)


def doc_for(*objects: Any) -> str:
    for obj in objects:
        docstring = getattr(obj, "docstring", None)
        if docstring is not None and docstring.value.strip():
            return docstring.value.strip()
    return ""


def md_escape(value: str) -> str:
    return value.replace("<", "&lt;").replace("{", "&#123;").replace("}", "&#125;")


def code_block(value: str, lang: str = "python") -> str:
    return f"```{lang}\n{value}\n```"


def frontmatter(title: str, description: str) -> str:
    return "\n".join(
        [
            "---",
            f"title: {json.dumps(title)}",
            f"description: {json.dumps(description)}",
            "---",
            "",
        ]
    )


def source_line(obj: Any) -> str:
    filepath = getattr(obj, "relative_filepath", None)
    lineno = getattr(obj, "lineno", None)
    if filepath is None or lineno is None:
        return ""
    return f"`{filepath}:{lineno}`"


def public_methods(cls: Class) -> list[Function]:
    methods: list[Function] = []
    for name, member in cls.members.items():
        if name.startswith("_"):
            continue
        target = target_for(member)
        if isinstance(target, Function):
            methods.append(target)
    return methods


def public_attributes(cls: Class) -> list[Attribute]:
    attrs: list[Attribute] = []
    for name, member in cls.members.items():
        if name.startswith("_"):
            continue
        target = target_for(member)
        if isinstance(target, Attribute):
            attrs.append(target)
    return attrs


def render_members(cls: Class) -> list[str]:
    lines: list[str] = []
    attributes = public_attributes(cls)
    if attributes:
        lines.extend(["## Attributes", ""])
        lines.extend(["| Name | Type | Description |", "| --- | --- | --- |"])
        for attr in attributes:
            annotation = annotation_for(attr) or "unknown"
            desc = md_escape(doc_for(attr)).replace("\n", " ") or ""
            lines.append(f"| `{attr.name}` | `{annotation}` | {desc} |")
        lines.append("")

    methods = public_methods(cls)
    if methods:
        lines.extend(["## Methods", ""])
        for method in methods:
            lines.extend([f"### `{method.name}`", ""])
            signature = signature_for(method)
            if signature:
                lines.extend([code_block(signature), ""])
            doc = doc_for(method)
            if doc:
                lines.extend([md_escape(doc), ""])
            src = source_line(method)
            if src:
                lines.extend([f"Source: {src}", ""])
    return lines


def render_page(name: str, exported_obj: Any, slug: str) -> ApiPage:
    target = target_for(exported_obj)
    category = category_for(name, target)
    kind = object_kind(target)
    signature = signature_for(exported_obj) or signature_for(target)
    doc = doc_for(exported_obj, target)
    description = doc.splitlines()[0] if doc else f"Generated API reference for graphrefly.{name}."

    lines = [
        frontmatter(name, description).rstrip(),
        "",
        MARKER,
        "",
        f"# `{name}`",
        "",
        f"**Kind:** {kind}",
        "",
    ]
    src = source_line(target)
    if src:
        lines.extend([f"**Source:** {src}", ""])
    if signature:
        lines.extend(["## Signature", "", code_block(signature), ""])
    elif isinstance(target, TypeAlias):
        lines.extend(["## Type", "", code_block(f"{name} = {value_for(target) or 'unknown'}"), ""])
    elif isinstance(target, Attribute):
        annotation = annotation_for(target)
        value = value_for(target)
        rendered = name
        if annotation:
            rendered += f": {annotation}"
        if value:
            rendered += f" = {value}"
        lines.extend(["## Value", "", code_block(rendered), ""])
    if doc:
        lines.extend(["## Description", "", md_escape(doc), ""])
    if isinstance(target, Class):
        lines.extend(render_members(target))

    markdown = "\n".join(lines).rstrip() + "\n"
    return ApiPage(name=name, slug=slug, category=category, markdown=markdown)


def render_index(pages: list[ApiPage]) -> str:
    by_category: dict[str, list[ApiPage]] = {}
    for page in pages:
        by_category.setdefault(page.category, []).append(page)
    lines = [
        frontmatter("API Reference", "Generated graphrefly Python API reference.").rstrip(),
        "",
        MARKER,
        "",
        "# API Reference",
        "",
        (
            "These pages are generated from `graphrefly.__all__` and source "
            "docstrings through `griffe`."
        ),
        "Update Python docstrings or exports, then rerun `pnpm --dir website docs:gen`.",
        "",
    ]
    for category, category_pages in by_category.items():
        lines.extend([f"## {category}", ""])
        for page in category_pages:
            lines.append(f"- [`{page.name}`](/api/{page.slug}/)")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_sidebar(pages: list[ApiPage]) -> str:
    by_category: dict[str, list[ApiPage]] = {}
    for page in pages:
        by_category.setdefault(page.category, []).append(page)
    groups = [
        {
            "label": category,
            "items": [{"label": page.name, "link": f"/api/{page.slug}"} for page in category_pages],
        }
        for category, category_pages in by_category.items()
    ]
    return f"export const apiSidebar = {json.dumps(groups, indent=2)};\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    module = load("graphrefly", search_paths=[str(SRC)])
    names = exported_names()
    slug_counts: dict[str, int] = {}
    for name in names:
        base = slug_for(name)
        slug_counts[base] = slug_counts.get(base, 0) + 1

    used_slugs: set[str] = set()
    pages: list[ApiPage] = []
    for name in names:
        slug = unique_slug_for(name, module[name], slug_counts, used_slugs)
        used_slugs.add(slug)
        pages.append(render_page(name, module[name], slug))
    changed: list[str] = []

    if not args.check:
        shutil.rmtree(API_DIR, ignore_errors=True)
        API_DIR.mkdir(parents=True, exist_ok=True)
    write_if_changed(API_DIR / "index.md", render_index(pages), args.check, changed)
    for page in pages:
        write_if_changed(API_DIR / f"{page.slug}.md", page.markdown, args.check, changed)
    write_if_changed(SIDEBAR_PATH, render_sidebar(pages), args.check, changed)

    if args.check and changed:
        print("Generated API docs are stale:")
        for path in changed:
            print(f"- {path}")
        raise SystemExit(1)
    print(f"generated {len(pages)} Python API pages")


if __name__ == "__main__":
    main()
