from collections.abc import Callable
from typing import Any

class Graph:
    def __init__(self, name: str | None = None) -> None: ...
    def state(self, value: object, name: str | None = None) -> Node: ...
    def state_empty(self, name: str | None = None) -> Node: ...
    def producer(self, callback: Callable[[], object], name: str | None = None) -> Node: ...
    def node(
        self,
        deps: list[Node],
        callback: Callable[[Ctx], object],
        name: str | None = None,
        partial: bool = False,
        complete_when_deps_complete: bool = True,
        error_when_deps_error: bool = True,
        terminal_as_real_input: bool = False,
        pausable: str | None = None,
        pull_id: str | None = None,
    ) -> Node: ...
    def _conformance_node(
        self,
        deps: list[Node],
        callback: Callable[[Ctx], object],
        name: str | None = None,
        partial: bool = False,
        complete_when_deps_complete: bool = True,
        error_when_deps_error: bool = True,
        terminal_as_real_input: bool = False,
        pausable: str | None = None,
        pull_id: str | None = None,
    ) -> Node: ...
    def derived(
        self,
        deps: list[Node],
        callback: Callable[..., object],
        name: str | None = None,
    ) -> Node: ...
    def effect(
        self,
        deps: list[Node],
        callback: Callable[..., object],
        name: str | None = None,
    ) -> Node: ...
    def batch(self, callback: Callable[[], object]) -> None: ...
    def describe(self) -> dict[str, Any]: ...
    def observe(self, callback: Callable[[str, str, object, int, int], object]) -> Subscription: ...
    def raise_pending_fatal(self) -> None: ...

class Node:
    def set(self, value: object) -> None: ...
    def send(self, value: object) -> None: ...
    def pause(self, lock_id: str) -> None: ...
    def resume(self, lock_id: str) -> None: ...
    def invalidate(self) -> None: ...
    def _up_dirty(self) -> None: ...
    def _up_teardown(self) -> None: ...
    def _conformance_up_pull(self, pull_id: str, params: object | None = None) -> None: ...
    def _conformance_up_pull_toward(
        self,
        toward_dep: int,
        pull_id: str,
        params: object | None = None,
    ) -> None: ...
    def _conformance_up_data_forbidden(self, value: object) -> None: ...
    def _down_resolved(self) -> None: ...
    def _down_dirty(self) -> None: ...
    def _down_invalidate(self) -> None: ...
    def _down_data_data_invalidate(self, first: object, second: object) -> None: ...
    def _down_data_complete(self, value: object) -> None: ...
    def _down_complete(self) -> None: ...
    def _down_teardown(self) -> None: ...
    def _down_error(self, message: str) -> None: ...
    def cache(self) -> object | None: ...
    def cache_entry(self) -> tuple[bool, object | None]: ...
    def status(self) -> str: ...
    def subscribe(self, callback: Callable[[str, object], object]) -> Subscription: ...

class Ctx:
    def dep_len(self) -> int: ...
    def data_entry(self, index: int) -> tuple[bool, object | None]: ...
    def wave_data(self, sentinel: object) -> list[list[list[object]]]: ...
    def terminal(self, index: int) -> bool | object: ...
    def emit(self, value: object) -> None: ...
    def state_entry(self) -> tuple[bool, object | None]: ...
    def set_state(self, value: object) -> None: ...
    def state_persist(self, on: bool = True) -> None: ...
    def on_invalidate(self, callback: Callable[[], object]) -> None: ...
    def on_deactivation(self, callback: Callable[[], object]) -> None: ...
    def _pull_context(self) -> tuple[str, object | None] | None: ...
    def _up_next_pull(
        self,
        pull_id: str,
        params: object | None = None,
        toward_dep: int | None = None,
    ) -> None: ...
    def _up_pull(
        self,
        pull_id: str,
        params: object | None = None,
        toward_dep: int | None = None,
    ) -> None: ...
    def _conformance_up_data(self, value: object) -> None: ...

class Subscription:
    def unsubscribe(self) -> None: ...

def version() -> str: ...
