from collections.abc import Callable
from typing import Any

class Graph:
    def __init__(self, name: str | None = None) -> None: ...
    def state(self, value: object, name: str | None = None) -> Node: ...
    def state_empty(self, name: str | None = None) -> Node: ...
    def producer(self, callback: Callable[[], object], name: str | None = None) -> Node: ...
    def node(
        self,
        deps: list[Node],
        callback: Callable[[Ctx], object],
        name: str | None = None,
    ) -> Node: ...
    def derived(
        self,
        deps: list[Node],
        callback: Callable[..., object],
        name: str | None = None,
    ) -> Node: ...
    def effect(
        self,
        deps: list[Node],
        callback: Callable[..., object],
        name: str | None = None,
    ) -> Node: ...
    def batch(self, callback: Callable[[], object]) -> None: ...
    def describe(self) -> dict[str, Any]: ...
    def observe(self, callback: Callable[[str, str, object, int, int], object]) -> Subscription: ...
    def raise_pending_fatal(self) -> None: ...

class Node:
    def set(self, value: object) -> None: ...
    def send(self, value: object) -> None: ...
    def pause(self, lock_id: str) -> None: ...
    def resume(self, lock_id: str) -> None: ...
    def invalidate(self) -> None: ...
    def _up_dirty(self) -> None: ...
    def _up_teardown(self) -> None: ...
    def cache(self) -> object | None: ...
    def cache_entry(self) -> tuple[bool, object | None]: ...
    def status(self) -> str: ...
    def subscribe(self, callback: Callable[[str, object], object]) -> Subscription: ...

class Ctx:
    def dep_len(self) -> int: ...
    def data_entry(self, index: int) -> tuple[bool, object | None]: ...
    def emit(self, value: object) -> None: ...
    def state_entry(self) -> tuple[bool, object | None]: ...
    def set_state(self, value: object) -> None: ...
    def state_persist(self, on: bool = True) -> None: ...
    def on_invalidate(self, callback: Callable[[], object]) -> None: ...
    def on_deactivation(self, callback: Callable[[], object]) -> None: ...

class Subscription:
    def unsubscribe(self) -> None: ...

def version() -> str: ...
